name = "spectux-pages"
type = "javascript"
account_id = "ee5bb4d92df279cd0216db945f145a6e"
compatibility_date = "2025-06-27"

[site]
bucket = "./"

[[kv_namespaces]]
binding = "INVITES"
id = "<YOUR_INVITES_NAMESPACE_ID>"
